### ISSUE TITLE
Table?

### ISSUE THREAD

**Issue by azerupi** [contradictioned/areweideyet#1]
Since you have added quite a few editors I would suggest using a table to have a quick overview of all supported features per editor.

**Comment by contradictioned** [comment]
Yep, I had this also in mind.
But I'm not quite sure, about the columns (assuming one row per editor).

I think, I'll collect some more feedback, and make my mind up :)

**Comment by azerupi** [comment]
If it is place you worry about you could rotate the header text: https://css-tricks.com/rotated-table-column-headers/ :)

**Comment by contradictioned** [comment]
The major concern is, I'm not sure how to handle, e.g. "build scripts", one editor/plugin ships support for rustc, the next for cargo. And I am not a fan of tables with footnotes, or much text in the table cells.

Thanks for the rotation ;)

**Comment by azerupi** [comment]
Ah yes I get it. I would avoid text in table cells too. Use unicode symbols like arewewebyet. And what you could do, is have both a table and a more detailed overview for each editor below the table. You could then link the different cells to the corresponding paragraph in the more detailed overview.

Just throwing in some ideas ;)
