### ISSUE TITLE
Emacs supports Go-to definition

### ISSUE THREAD

**Issue by Wilfred** [contradictioned/areweideyet#10]
This is part of racer, so perhaps it doesn't make sense a separate column? Alternatively, there are two tags implementations available for Rust (both standalone tools, though I think only Emacs and vim support tags).

**Comment by contradictioned** [comment]
I added a ✓ for goto-definition.
But in general I think, this is useful to have two seperate columns, because they're different features.
And afaik kate, for example, can has autocompletion but no goto definition.

I will look into tags, thanks for the hint.

**Comment by Wilfred** [comment]
Thanks!

For what it's worth, the two tags implementations are [rusty-tags](https://github.com/dan-t/rusty-tags) and [there's a tags configuration shipped in the rustc source code](https://www.reddit.com/r/rust/comments/1rlv79/did_you_know_you_can_generate_tags_for_rust/).
