### ISSUE TITLE
LetsEncrypt Certificate Expired Oct 22

### ISSUE THREAD

**Issue by j4ng5y** [contradictioned/areweideyet#100]
![Screen Shot 2020-10-22 at 3 45 27 PM](https://user-images.githubusercontent.com/44218998/96928792-bc266600-147e-11eb-95b5-d421a239fc2a.png)

I wish I could just PR this, but I can't 🤷

**Comment by contradictioned** [comment]
Yep, thanks for reporting. Could maybe take some more hours (have changed DNS entries)
