### ISSUE TITLE
VS Code

### ISSUE THREAD

**Issue by retep998** [contradictioned/areweideyet#13]
VS Code totally has syntax highlighting for Rust out of the box.
Since it is based on the same core as Atom, I'd likely classify it in the same category as Atom, so text editors.

**Comment by contradictioned** [comment]
Do you know if there is more that is supported by VS Code?
Like, can the atom plugins be used there?

Because if it only highlights .rs files, I'd tend not to include it (yet).
And for fairness reasons maybe put it into a list like "syntax highlightning supported" together with geany...

**Comment by jaxx** [comment]
There is now plugin for Rust- https://marketplace.visualstudio.com/items/saviorisdead.RustyCode. It completes code using Racer and format code using rustfmt.

**Comment by contradictioned** [comment]
It already works fine.. I think, that's enough to include it ;)
