### ISSUE TITLE
Vim has code snippets for rust!

### ISSUE THREAD

**Issue by matthiasbeyer** [contradictioned/areweideyet#14]
As there is UltiSnips and vim-snippets:

https://github.com/honza/vim-snippets/blob/master/UltiSnips/rust.snippets

Also, the user can write own snippets with UltiSnips!
So, vim has code-snippets via plugins!

:smile:

**Comment by contradictioned** [comment]
Well, writing own snippets is probably possible in every editor, so that doesn't count ;)

Thanks for the information, it's already live!
