### ISSUE TITLE
Brackets

### ISSUE THREAD

**Issue by rrandom** [contradictioned/areweideyet#17]
hi, I wrote a Brackets extenison https://github.com/rrandom/Brackets-Rust-IDE 
support:
Syntax highlighting
Code Completion (via racer)
Quick Edit
Linting

**Comment by contradictioned** [comment]
Hi, sorry for the late response;
In a6d98df I added this plugin, but I hesitate to add Brackets to the table. I think, I have to start think about which editors are meaningful to have there.

Thanks for the input!
