### ISSUE TITLE
Atom.io

### ISSUE THREAD

**Issue by farodin91** [contradictioned/areweideyet#2]
Adding Are we IDE yet? for Atom.io

**Comment by contradictioned** [comment]
I am writing at it right now ;)

**Comment by farodin91** [comment]
nice

**Comment by farodin91** [comment]
My Current Setup of Packages is:
- language-rust
- racer
- linter-rust (is to slow for me)

**Comment by contradictioned** [comment]
Thx, basically the same list as in https://www.reddit.com/r/rust/comments/3h7fc6/are_we_ide_yet_an_approach_to_an_overview/cu4wk0s

In with a80d1cdfbd8ac50957fc6359247ff8cedab18334
