### ISSUE TITLE
YouCompleteMe

### ISSUE THREAD

**Issue by durka** [contradictioned/areweideyet#21]
YouCompleteMe for Vim is [ready](http://blog.jwilm.io/youcompleteme-rust) and obsoletes vim-racer.

**Comment by contradictioned** [comment]
I added the link, but I don't know how to handle the "obsoletes vim-racer" part.
Is vim-racer really not longer important or is YouCompleteMe an alternative plugin and vim-users have the choice between them?

**Comment by durka** [comment]
I guess they are alternatives.

**Comment by contradictioned** [comment]
Okay, then I think, I'll let both of them in the list. Thanks!
