### ISSUE TITLE
Tokamak supplies all the fields

### ISSUE THREAD

**Issue by vertexclique** [contradictioned/areweideyet#26]
https://vertexclique.github.io/tokamak/

Moreover it has cargo, toolchain and terminal support 
- Run in its own terminal
- Run tests for cargo based projects
- Build your cargo project
- Run cargo binaries
- Manage toolchains
  etc.

P.S.:
I was going to implement IDE like features for Rust(because of that I called it as IDE at the beginning). But I came across this:
https://github.com/rust-lang/rfcs/blob/master/text/1317-ide.md
Which will take place in future.

@contradictioned

**Comment by PhiLhoSoft** [comment]
This issue can be better with a link...
https://vertexclique.github.io/tokamak/
Learned about this "IDE" only recently.
Based on Atom, so I am not sure how it differs from existing packages like `language-rust`, `racer`, `linter-rust`.
Looks like a meta-package, grouping these and adding more...

**Comment by vertexclique** [comment]
Yeah it is just a meta package but it also gives you option to:

- Run terminal
- Run tests
- Build your cargo project
- Run cargo binaries
- Manage toolchains
etc.

**Comment by contradictioned** [comment]
The plugin was added a while ago; thanks for the input, and best luck for your [comebak](https://github.com/vertexclique/tokamak/commit/9924ce3936d6cf2c2bff922158af219761fd2a86) ;)

**Comment by vertexclique** [comment]
Thanks :) P.S. It supports code formatting out of the box with both auto formatting and manual formatting.
