### ISSUE TITLE
New IDE: Ride

### ISSUE THREAD

**Issue by madeso** [contradictioned/areweideyet#30]
Shameless plug for my own IDE: https://github.com/madeso/ride
As far as I can tell it has the same features as SolidOak, but there is no cool homepage and there aren't any prebuilt downloads (yet).

**Comment by contradictioned** [comment]
Since I think, I have an solution for the problem of selecting which editors/ides to include, I'll probably add this to the lis, thanks ;)

**Comment by contradictioned** [comment]
Oh, I found a way! Welcome to the list :wave:

I have actually not found more features than syntax highlighting; if there's more, please tell me.
