### ISSUE TITLE
Sublime has Syntax Checking support

### ISSUE THREAD

**Issue by Jayflux** [contradictioned/areweideyet#32]
I've noticed that sublime isn't listed as syntax checking on here:
https://areweideyet.com/#sublime

But this has now been added:
https://github.com/rust-lang/sublime-rust#syntax-checking

**Comment by adambadawy** [comment]
Also of note, Sublime Text includes Rust syntax highlighting by default as well.

**Comment by Jayflux** [comment]
@contradictioned @Manishearth

**Comment by contradictioned** [comment]
Actually, it includes the whole Rust package, which also means, snippets and the fancy new compiler lints :)
