### ISSUE TITLE
Add info about debugging support to the table

### ISSUE THREAD

**Issue by peterholak** [contradictioned/areweideyet#33]
I see that some IDEs already contain integrated debugging support. As this is one of the most important IDE features for many people, I think you should add it to the overview table :smiley:.

**Comment by contradictioned** [comment]
Well, it is in the table; but I strongly think that the information is not complete yet.
Todo:

- [ ] Atom
- [ ] BBedit
- [ ] Emacs
- [ ] Textadept
- [ ] Sublime
- [ ] Vim
- [ ] IntelliJ

**Comment by worikgh** [comment]
Emacs has debugging, via rust-gdb

Works well for me
