### ISSUE TITLE
GEdit syntax highlighting support

### ISSUE THREAD

**Issue by chronologicaldot** [contradictioned/areweideyet#35]
Just what is says. It's not comprehensive (doesn't highlight common standard library functions other than maybe a couple).
https://github.com/chronologicaldot/GEdit-Rust-lang

Notably, of course, Racer already has auto-completion. What I've posted is just a simple syntax highlighter for anyone not looking for something fancy.

**Comment by chronologicaldot** [comment]
Notably, of course, Racer already has auto-completion. What I've posted is just a simple syntax highlighter for anyone not looking for something fancy.

**Comment by contradictioned** [comment]
Thanks, added it (and the other rust-syntax definition as well ;) )
