### ISSUE TITLE
https://areweideyet.com/ has not been updated in quite some time

### ISSUE THREAD

**Issue by tarcieri** [contradictioned/areweideyet#36]
The IntelliJ plugin now has a number of features https://areweideyet.com/ says it does not. These were added in c7bfbbe, but it looks like the site itself hasn't been updated in awhile.

**Comment by contradictioned** [comment]
Hmm.. thanks for the heads up. Should have been fixed with the current issues I am working on/completing. Not sure if I just forgot to rsync the previous version or if something else happened. If it is out of date again, please ping me ;)
