### ISSUE TITLE
add sublime-rust to Sublime packages

### ISSUE THREAD

**Issue by Jayflux** [contradictioned/areweideyet#38]
https://github.com/rust-lang/sublime-rust is the official rust-lang supported plugin for Sublime Text 3.
I'm surprised it's not added to the list under sublime text 2/3

It's soon to be called Rust Enhanced (to avoid confusion with the default plugin)

**Comment by contradictioned** [comment]
Oh, I actually thought this was the default plugin, because it is listed as `Rust` here https://packagecontrol.io/packages/Rust and the installed one seems to have the same features.
I'll re-add this; thanks for the heads-up!
