### ISSUE TITLE
Some additional Sublime Text packages

### ISSUE THREAD

**Issue by wldcordeiro** [contradictioned/areweideyet#4]
* [Linting](https://packagecontrol.io/packages/SublimeLinter-contrib-rustc)
* [Code Formatting](https://packagecontrol.io/packages/RustCodeFormatter)

**Comment by jaxx** [comment]
Sublime has very good linting actually, I don't understand why this hasn't been added to the website yet.

**Comment by contradictioned** [comment]
Me neither, I think, I wanted to take a closer look at these packages and then forgot, sorry; and thanks for the suggestions!
