### ISSUE TITLE
Sublime 2/3: Rust plugin replaced with Rust Enhanced.

### ISSUE THREAD

**Issue by hosaka** [contradictioned/areweideyet#42]
Hello,

Sublime 2/3 section of we webpage links to the non-existing plugin "Rust". Afaik, this was replaced by [Rust Enhanced](https://packagecontrol.io/packages/Rust%20Enhanced).

**Comment by contradictioned** [comment]
IIRC, it was more a renaming, because sublime now has also a default plugin called "Rust". But anyways, thanks for the headsup!
