### ISSUE TITLE
RustDT is no longer actively maintained

### ISSUE THREAD

**Issue by HighCommander4** [contradictioned/areweideyet#53]
The README for [RustDT](https://github.com/RustDT/RustDT/) (the Rust plugin for Eclipse) says it's no longer actively maintained. Should we make a note of this?

Is anyone aware of another Rust plugin for Eclipse that is maintained, that we could list instead?

**Comment by contradictioned** [comment]
I tried to find something, but found nothing. The author [sketched](http://pureconcepture.blogspot.de/2017/07/goodbye-to-eclipse-end-of-era-for.html) eclipse to be losing users in favour of others like IntelliJ and VSCode. Maybe we won't see another plugin soon; maybe we will. In either way, I'll mark it as discontinued for now, thanks for the heads-up!

**Comment by HighCommander4** [comment]
There is now [Eclipse Corrosion](https://github.com/eclipse/corrosion), which is based on RLS.
