### ISSUE TITLE
Textadept overrated here?

### ISSUE THREAD

**Issue by vi** [contradictioned/areweideyet#54]
I don't see "Go to definition" feature.

And code completion without racer seems to be rather weak, so it should be `✓2` rather than `✓1`. And with racer it [crashes for me](https://bitbucket.org/a_baez/ta-rust/issues/6/segmentation-fault-when-using-racer).

**Comment by contradictioned** [comment]
This might be, it was some years ago that I tested it; I'll have a look.

**Comment by contradictioned** [comment]
Further, with the current version of rustfmt it does not work, as the plugin calls rustfmt with the non-existent param `--write-mode`... I'll mark it as out-of-date for now.
