### ISSUE TITLE
Add Atom IDE package?

### ISSUE THREAD

**Issue by Pfeil** [contradictioned/areweideyet#55]
I wonder if there is a reason not to mention `ide-rust` for atom yet?

While the currently described packages are working and still an option, there are new possibilities. Atom has now support for so called [ide packages](https://ide.atom.io/) based on the language server protocol. There is a pretty good `ide-rust` [package](https://atom.io/packages/ide-rust). It has the limitations of `rls`, including missing/limited support for examples. It does support documentation tooltips and does not really work well together with linter packages, since it replaces them and displays errors in a dedicated ui element. While it's a bit ugly, it should be possible to use them together, though.

Except for the `ide-rust` package you need `language-rust` so Atom knows the language and can show the rust IDE. I also use it together with `cargo-build`. You get a pretty neat IDE using these three packages only, and I thing it's worth mentioning.

**Comment by contradictioned** [comment]
So to understand this correctly: You install `atom-ide-ui` and then `ide-rust` in order to get a special view for rust editing?

**Comment by Pfeil** [comment]
Basically, yes. Actually you only need to install `ide-rust` and it will tell you that it also needs to install `atom-ide-ui` as a dependency. It's getting as much as it can out of `rls` and the official `atom-ide-ui`. It basically looks like the video on the atom ide website ( https://ide.atom.io/ ) shows. It works pretty good, as long as `rls` does. It will also install `rls` in the background if it is not installed in the toolchain selected in the settings of `ide-rust`.

**Comment by aldonogueira** [comment]
I used to install a few package for Rust on Atom. Now I just install RLS on my system and ide-rust on Atom. Much simpler
