### ISSUE TITLE
Link is outdated.

### ISSUE THREAD

**Issue by Pfeil** [contradictioned/areweideyet#67]
https://github.com/contradictioned/areweideyet/blob/cc0ba1937a6e633f5e509206a852ef287d9a42ab/index.jade#L21

I have no idea what happened to it. The article does not seem to exist anymore.

**Comment by contradictioned** [comment]
Iirc that page was a plan from zero to first ide support, and since this has matured (e.g., with [rls](https://github.com/rust-lang-nursery/rls) there) they removed this page. I'll delete it, thanks!

**Comment by rugk** [comment]
The link is still there… 🤨

**Comment by HoLLy-HaCKeR** [comment]
Change is not live on the website?

**Comment by sgrove** [comment]
Was going to report this as well, seems to still be there
