### ISSUE TITLE
Emacs has a working RLS client package

### ISSUE THREAD

**Issue by Follpvosten** [contradictioned/areweideyet#72]
To be found [here](https://github.com/emacs-lsp/lsp-rust). They call it unstable, but it works very good in my experience (I've used it for a couple of hours), way better and faster than emacs-racer.

I don't know exactly what to do, but maybe at least mention it somewhere?

Update: It was working fine earlier today - I can't get it to work right now for some reason. Oh well.

**Comment by contradictioned** [comment]
Ok, this repository has been archived in the meantime; so it is lsp-mode I guess.
