### ISSUE TITLE
Broken link to https://www.rust-lang.org/ides.html

### ISSUE THREAD

**Issue by fingolfin** [contradictioned/areweideyet#76]
At the top of your page, in the sentence "Did you know, there is a plan for IDEs ", the word "plan" is a link to https://www.rust-lang.org/ides.html -- but this gives a 404 error. I briefly tried to find out if this page moved elsewhere, but was unable to locate it.

**Comment by contradictioned** [comment]
I think, the ide-page was also outdated, so it was removed. I'll remove the link, thanks.
