### ISSUE TITLE
Add gitpod.io

### ISSUE THREAD

**Issue by JonahHenriksson** [contradictioned/areweideyet#78]
I haven't tried this online IDE out yet, but it promises Rust support, so I thought it would be good to suggest: [gitpod.io](https://www.gitpod.io)

**Comment by contradictioned** [comment]
Hey, sorry for being "a little late". I think, Gitpod makes it quite clear, that the editor/ide part of it is VSCode. If someone looks at areweideyet.com for Gitpod, I think, they would look also for VSCode.
