### ISSUE TITLE
MIcro editor has a good basic rust support

### ISSUE THREAD

**Issue by rochacbruno** [contradictioned/areweideyet#88]
https://micro-editor.github.io/

- Syntax Highlight
- Rust Plugins https://github.com/tommyshem/micro-rust-plugin
- easy to extend https://github.com/rochacbruno/i3_and_dotfiles/blob/master/move_to.config/micro/init.lua

**Comment by contradictioned** [comment]
Cool. I think this can go into the "more"-Section.
